version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: yapi_mongodb
    volumes:
      - ./mongo/db:/data/db
  web:
    image: tanshion/yapi
    container_name: yapi_web
    depends_on:
      - mongodb
    ports:
      - "9300:3000"
    volumes:
      - ./yapi:/my-yapi
  install:
    image: tanshion/yapi
    depends_on:
      - mongodb
    volumes:
      - ./yapi:/my-yapi
    entrypoint: yapi
    command:
      - /bin/sh
      - -c
      - |
        install -v v1.8.7
        plugin --name yapi-plugin-import-swagger-customize
  update:
    image: tanshion/yapi
    depends_on:
      - mongodb
    volumes:
      - ./yapi:/my-yapi
    entrypoint: yapi
    command: update
